// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt0IUEedt82qUAbK0gqJxdeKBKh0iYxzo',
    appId: '1:1032655111052:web:a5eb5d1c417beeefdf8ca9',
    messagingSenderId: '1032655111052',
    projectId: 'amigo-invisible-c6411',
    authDomain: 'amigo-invisible-c6411.firebaseapp.com',
    storageBucket: 'amigo-invisible-c6411.firebasestorage.app',
    measurementId: 'G-5XM32TEPEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmfCtZ-c1502kxnvMGmheArvf6VJyNcFc',
    appId: '1:752362678954:android:ac06b7ae091f4420b07ed3',
    messagingSenderId: '752362678954',
    projectId: 'amigo-invisible-limpio',
    storageBucket: 'amigo-invisible-limpio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6ZKUXWkGAbXvjWtvmhSkuolBdT9mnn2I',
    appId: '1:752362678954:ios:97f2028933d1f7afb07ed3',
    messagingSenderId: '752362678954',
    projectId: 'amigo-invisible-limpio',
    storageBucket: 'amigo-invisible-limpio.firebasestorage.app',
    iosBundleId: 'com.example.amigoInvisible',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_-ujt45EFk1OeFQUQ8zcIFvfwu2J59-o',
    appId: '1:1032655111052:ios:f65f0a89e5119ca9df8ca9',
    messagingSenderId: '1032655111052',
    projectId: 'amigo-invisible-c6411',
    storageBucket: 'amigo-invisible-c6411.firebasestorage.app',
    iosBundleId: 'com.example.amigoinvisible',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt0IUEedt82qUAbK0gqJxdeKBKh0iYxzo',
    appId: '1:1032655111052:web:fafc936a46847eb1df8ca9',
    messagingSenderId: '1032655111052',
    projectId: 'amigo-invisible-c6411',
    authDomain: 'amigo-invisible-c6411.firebaseapp.com',
    storageBucket: 'amigo-invisible-c6411.firebasestorage.app',
    measurementId: 'G-XWXCK018KK',
  );
}